spring:
  application:
    name: notification-service
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:json.trusted.packages: '*'
        spring.json.type.mapping:
          orderConfirmation: com.notificationservice.order.OrderConfirmation,
          paymentConfirmation: com.notificationservice.payment.PaymentConfirmation
  config:
    import: optional:configserver:http://localhost:8088
