server:
  port: 9054

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/notification-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/